CREATE TABLE IF NOT EXISTS auctions (
    id                   BIGINT AUTO_INCREMENT PRIMARY KEY,
    product_id           BIGINT NOT NULL UNIQUE,
    merchant_id          BIGINT NOT NULL,
    start_price          DECIMAL(15,2) DEFAULT 0.00,
    bid_increment_type   ENUM('fixed','percent') NOT NULL,
    bid_increment_value  DECIMAL(15,2) NOT NULL,
    ceiling_price        DECIMAL(15,2) NULL,
    duration_seconds     INT NOT NULL,
    auto_extend_seconds  INT DEFAULT 15,
    max_extend_count     INT DEFAULT 5,
    current_extend_count INT DEFAULT 0,
    status               ENUM('pending','active','ended_sold','ended_no_bid','cancelled') DEFAULT 'pending',
    current_price        DECIMAL(15,2) DEFAULT 0.00,
    highest_bidder_id    BIGINT NULL,
    cancel_reason        VARCHAR(500),
    version              INT DEFAULT 0,
    started_at           DATETIME NULL,
    ended_at             DATETIME NULL,
    cancelled_at         DATETIME NULL,
    created_at           DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at           DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (product_id) REFERENCES products(id),
    FOREIGN KEY (merchant_id) REFERENCES users(id),
    INDEX idx_merchant (merchant_id),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
