CREATE TABLE IF NOT EXISTS auction_bid_commands (
    id                    BIGINT AUTO_INCREMENT PRIMARY KEY,
    command_id            VARCHAR(36) NOT NULL UNIQUE,
    auction_id            BIGINT NOT NULL,
    user_id               BIGINT NOT NULL,
    idempotency_key       VARCHAR(128) NULL,
    core_idempotency_key  VARCHAR(128) NOT NULL,
    amount                DECIMAL(15,2) NOT NULL,
    status                ENUM('queued','processing','accepted','rejected','failed') NOT NULL DEFAULT 'queued',
    failure_reason        VARCHAR(500) NULL,
    bid_id                BIGINT NULL,
    order_id              BIGINT NULL,
    auction_version       BIGINT NULL,
    attempts              INT NOT NULL DEFAULT 0,
    processing_started_at DATETIME NULL,
    processed_at          DATETIME NULL,
    created_at            DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at            DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_bid_command_idempotency (auction_id, user_id, idempotency_key),
    UNIQUE KEY uk_bid_command_core_key (core_idempotency_key),
    FOREIGN KEY (auction_id) REFERENCES auctions(id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (bid_id) REFERENCES bids(id),
    FOREIGN KEY (order_id) REFERENCES orders(id),
    INDEX idx_bid_command_owner (auction_id, user_id, command_id),
    INDEX idx_bid_command_auction_status (auction_id, status, id),
    INDEX idx_bid_command_status_created (status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
